### ISSUE TITLE
Underflow crash during large calculation

### ISSUE THREAD

**Issue by charlieb** [charlieb/paint#4]
During a 100x100 run this happened:

Make Grid Elapsed: 0.4094867706298828
Shuffle Elapsed: 338.60786724090576
Draw Elapsed: 9.693838119506836
......Traceback (most recent call last):
File "paint.py", line 310, in <module>
main()
File "paint.py", line 301, in main
iterate(grid, links, link_lens)

**Comment by charlieb** [comment]
Underflow means that something got so close to zero that it became zero. I don't care about that for this application.
